export const PRODUCTS_DATA = "products_data"
export const CATEGORY_DATA = "category_data"
export const REVIEW_DATA = "review_data"
export const PRODUCTS_STORAGE = "products_storage"
export const CATEGORY_STORAGE = "category_storage"